### ISSUE TITLE
Tab content disappears

### ISSUE THREAD

**Issue by alejogamboa** [GabrielAlva/SwiftPages#13] opened 2015-08-26 15:10 UTC
I am using your component inside a view controller that belongs to a UITabBarController. The content of the tabs disappears after you take the app into the background and bring it to the foreground again or, sometimes, when you go to another view controller and return. I am running the example and it happens too. By the way, I am using XCode 7 beta 5 and running in iPhone 6; I don't know if that has something to do with the problem

**Comment by GabrielAlva** [comment] 2015-10-12 04:10
Hi, I see the problem. I just updated the project to iOS 9, its ok when you create it as a fully programmatic view (1st option on the demo), but I see the problem when its created as a view on the storyboard. I'll fix it but in the meantime you can use it programmatically.

**Comment by fergonzalez** [comment] 2015-12-22 21:24
Did you find any solution for this issue?

**Comment by ADevelopStudio** [comment] 2015-12-29 03:33
Also need a solution...

**Comment by michaelrabelo** [comment] 2016-01-02 01:42
have you found any solution ? I tried both as a view on the storyboard and programmatically but the problem keep happening on iOS 9.

**Comment by ghost** [comment] 2016-01-11 14:27
ios 7.2, Iphone 6... views disappearing when coming back from a "details view" of a tableviewcell. Need solution plz

Update: Couldn't wait for fix so my Solution was switching to the CarbonKit Swift library, does exactly the same with more modifiers/options

**Comment by lemak5** [comment] 2016-01-22 13:34
Hi, same problem here. Also need a solution. Thanks

**Comment by GabrielAlva** [comment] 2016-02-02 05:40
Hi, I pushed a fix, check now please. The VC that contains swift pages view needed to have this line:
`self.automaticallyAdjustsScrollViewInsets = false`
Otherwise it modifies the insets of the scrollview within the swift pages view, its a behaviour I didnt expect. You can see it on the example.

**Comment by michaelrabelo** [comment] 2016-02-02 08:53
Thank you. I tested here and now it works perfectly.

**Comment by alejogamboa** [comment] 2016-02-02 17:44
Great. It works perfect. Thaaaaaanks a lot!! Greetings from Colombia

**Comment by michaelrabelo** [comment] 2016-02-09 15:09
The problem continues after updating to iOS 9.2.1. When I use the updated version of SwiftPages my App crashes when going to background. The problem seems to be in orientationDidChange() function. Also the animatedBar is not showing until the topBar is tapped. If I find a solution to any of this problems I'll let you know. For now thank you for this awesome Swift class!

**Comment by GabrielAlva** [comment] 2016-02-09 22:20
Hi, Thanks for catching that bug, I pushed the fix, please check it out and let me know if you find any other issues with it or the new orientation support!

**Comment by michaelrabelo** [comment] 2016-02-10 02:07
Hello. Thank you for the fast response. The problem with the background mode was resolved, however, the contents within the scrollview continues to disappear even when using **_self.automaticallyAdjustsScrollViewInsets = false_** when the app returns to foreground, and now even the topBar disappears.

**Comment by GabrielAlva** [comment] 2016-02-10 02:29
I can't reproduce it, could you please give me the steps. By the way, try cleaning the projects and then see if the problem still happens :)

**Comment by GabrielAlva** [comment] 2016-02-10 02:50
I saw the bug, happens sporadically, let me push a fix in some hours.

**Comment by michaelrabelo** [comment] 2016-02-11 12:11
Hi Gabriel. Thank you!
I just wanna add one more thing to the issues list. On iPhone 6 Plus devices when the screen rotation is locked the app loads just fine, but when the screen is set to rotate depending on the device position the app doesn't load.

**Comment by GabrielAlva** [comment] 2016-02-14 08:19
Hi,
I finished solving the disappearance of the content view bug and debugging overall, I also checked for memory leaks and found none. Please check it out and let me know if any other issues arise!
@Michaeldrm  Im not sure how you implemented the selective rotation, if you could open another issue describing it better I can help you further :)

**Comment by michaelrabelo** [comment] 2016-02-15 09:04
It is working as expected now. Thank you! I'll take a look in my project. If the rotation problem persists I will open another issue.

**Closed as completed** 2016-02-23 01:51 UTC
